[window]
startup_mode = "Fullscreen"
decorations = "None"
dynamic_padding = true

[font.normal]
family = "MesloLGS Nerd Font"

[font.bold]
family = "MesloLGS Nerd Font"

[font.italic]
family = "MesloLGS Nerd Font"

[font.bold_italic]
family = "MesloLGS Nerd Font"

[colors.primary]
foreground = "#ABB2BF"
background = "#1E2127"

[colors.normal]
black = '#1E2127'
red = '#E06C75'
green = '#98C379'
yellow = '#D19A66'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#56B6C2'
white = '#ABB2BF'

[colors.bright]
black = '#5C6370'
red = '#E06C75'
green = '#98C379'
yellow = '#D19A66'
blue = '#61AFEF'
magenta = '#C678DD'
cyan = '#56B6C2'
white = '#FFFFFF'

[colors.cursor]
text = '#1E2127'
cursor = '#FFFFFF'

[colors.selection]
text = '#1E2127'
background = '#FFFFFF'
